### ISSUE TITLE
NameError: global name 'qtSensorAdjustment' is not defined

### ISSUE THREAD

**Issue by petegibson** [whoobee/sensor_odom_manager#1]
Hi, thanks for publishing this project. 

I'm getting an error when launching 

> Traceback (most recent call last):
> File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner                                                                 
>     self.run()
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/timer.py", line 234, in run
>     self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
>   File "/home/auser/ros/vendor/src/sensor_odom_manager/src/sensor_odom_manager/sensor_odom_manager_node.py", line 200, in fast_timer
>     self.pub_odometry(time_now)
>   File "/home/auser/ros/vendor/src/sensor_odom_manager/src/sensor_odom_manager/sensor_odom_manager_node.py", line 147, in pub_odometry
>     self.qtAdjustedRot = tf.transformations.quaternion_multiply(qtRot, tf.transformations.quaternion_inverse(qtSensorAdjustment))
> NameError: global name 'qtSensorAdjustment' is not defined

ROS Melodic on Ubuntu 18.04

I had a look but wasn't sure if that was supposed to refer to the qtSensorAdjustmentTool quaternion or not.

https://github.com/whoobee/sensor_odom_manager/blob/2522e68c38483cfaf1830a89481e4faf34153992/src/sensor_odom_manager/sensor_odom_manager_node.py#L147

**Comment by whoobee** [comment]
Hello @petegibson,

really sorry for the late response :(

indeed it looks like the error was because of a typo when calculating the qt inverse.
strange how this got passed, since I am using the same codebase and I have no errors...

the error should be fixed now in the latest commit: https://github.com/whoobee/sensor_odom_manager/commit/de51e4d3d67b887f9eeaa6d900701c8707842980
